"""Adding test models for resource and tag

Revision ID: e8ca2e61866c
Revises: 
Create Date: 2022-04-30 19:04:49.867500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ca2e61866c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_resource_id'), 'resource_resource', ['id'], unique=True)
    op.create_index(op.f('ix_resource_resource_name'), 'resource_resource', ['name'], unique=True)
    op.create_index(op.f('ix_resource_resource_slug'), 'resource_resource', ['slug'], unique=True)
    op.create_table('tag_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag_id'), 'tag_tag', ['id'], unique=True)
    op.create_index(op.f('ix_tag_tag_name'), 'tag_tag', ['name'], unique=True)
    op.create_index(op.f('ix_tag_tag_slug'), 'tag_tag', ['slug'], unique=True)
    op.create_table('resource_resourcetagassociation',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_resource.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'resource_id')
    )
    op.create_index('tag_resource_association_idx_tag_resource', 'resource_resourcetagassociation', ['resource_id', 'tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag_resource_association_idx_tag_resource', table_name='resource_resourcetagassociation')
    op.drop_table('resource_resourcetagassociation')
    op.drop_index(op.f('ix_tag_tag_slug'), table_name='tag_tag')
    op.drop_index(op.f('ix_tag_tag_name'), table_name='tag_tag')
    op.drop_index(op.f('ix_tag_tag_id'), table_name='tag_tag')
    op.drop_table('tag_tag')
    op.drop_index(op.f('ix_resource_resource_slug'), table_name='resource_resource')
    op.drop_index(op.f('ix_resource_resource_name'), table_name='resource_resource')
    op.drop_index(op.f('ix_resource_resource_id'), table_name='resource_resource')
    op.drop_table('resource_resource')
    # ### end Alembic commands ###
